# Generated by Django 3.2.4 on 2022-12-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentIdApp', '0003_iddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iddata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='iddata',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
