# Generated by Django 3.2.4 on 2022-12-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentIdApp', '0004_auto_20221222_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=30)),
                ('mother', models.CharField(max_length=30)),
                ('phno', models.IntegerField()),
                ('ephno', models.IntegerField()),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('role', models.CharField(max_length=20)),
                ('schoolname', models.CharField(max_length=50)),
                ('rollNumber', models.IntegerField()),
                ('standard', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=30)),
                ('mother', models.CharField(max_length=30)),
                ('phno', models.IntegerField()),
                ('ephno', models.IntegerField()),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('role', models.CharField(max_length=20)),
                ('schoolname', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Iddata',
        ),
    ]
