# Generated by Django 3.2.4 on 2022-12-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentIdApp', '0008_auto_20221227_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=20),
        ),
    ]
