# Generated by Django 3.2.4 on 2023-01-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentIdApp', '0010_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
